/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DBUtility.java
 *
 * Created on Dec 12, 2011, 11:47:43 AM
 */
package com.agrologic.app.ui;

import com.agrologic.app.dao.DataDao;
import com.agrologic.app.dao.impl.DataDaoImpl;
import java.sql.SQLException;

/**
 *
 * @author Administrator
 */
public class DBUtility extends javax.swing.JFrame {

    long startDataId;
    long endDataId;
    long tableid;
    long screenid;
    long programid;
    String show;
    int pos;
    DataDao dataDao;

    /** Creates new form DBUtility */
    public DBUtility() {
        initComponents();

        IndexedFocusTraversalPolicy policy = new IndexedFocusTraversalPolicy();
        policy.addIndexedComponent(txtStartDataId);
        policy.addIndexedComponent(txtEndDataId);
        policy.addIndexedComponent(txtTableId);
        policy.addIndexedComponent(txtScreenId);
        policy.addIndexedComponent(txtProgramId);
        policy.addIndexedComponent(txtShow);
        policy.addIndexedComponent(txtPos);
        setFocusTraversalPolicy(policy);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtStartDataId = new javax.swing.JTextField();
        txtEndDataId = new javax.swing.JTextField();
        txtTableId = new javax.swing.JTextField();
        txtScreenId = new javax.swing.JTextField();
        txtProgramId = new javax.swing.JTextField();
        txtShow = new javax.swing.JTextField();
        txtPos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DB Utility for AgroDB");

        txtStartDataId.setAutoscrolls(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Start Position");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Show ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Table ID");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Start Data ID");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Program ID");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Screen ID");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("One");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Many");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("End Data ID");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtScreenId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTableId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgramId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStartDataId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEndDataId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtEndDataId, txtPos, txtProgramId, txtScreenId, txtShow, txtStartDataId, txtTableId});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStartDataId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jRadioButton1)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEndDataId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton2)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTableId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScreenId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgramId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtEndDataId, txtPos, txtProgramId, txtScreenId, txtShow, txtStartDataId, txtTableId});

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel8.setText("Log ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dataDao = new DataDaoImpl();

        if (fieldsNotEmtpty()) {
            if (jRadioButton1.isSelected()) {
                startDataId = Long.parseLong(txtStartDataId.getText());
                tableid = Long.parseLong(txtTableId.getText());
                screenid = Long.parseLong(txtScreenId.getText());
                programid = Long.parseLong(txtProgramId.getText());
                show = txtShow.getText();
                pos = Integer.parseInt(txtPos.getText());
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            dataDao.insertDataToTable(programid, screenid, tableid, startDataId, show, pos);
                        } catch (SQLException ex) {
                            jTextArea2.append("Error adding dataids ");
                            for (Throwable e : ex) {
                                if (e instanceof SQLException) {
                                    e.printStackTrace(System.err);
                                    Throwable t = ex.getCause();
                                    while (t != null) {
                                        jTextArea2.append("Cause: " + t + "\n");
                                        t = t.getCause();
                                    }

                                }
                            }
                        }
                        jTextArea2.append("All data are added\n");
                    }
                }).start();

            } else {
                startDataId = Long.parseLong(txtStartDataId.getText());
                endDataId = Long.parseLong(txtEndDataId.getText());
                tableid = Long.parseLong(txtTableId.getText());
                screenid = Long.parseLong(txtScreenId.getText());
                programid = Long.parseLong(txtProgramId.getText());
                show = txtShow.getText();
                pos = Integer.parseInt(txtPos.getText());
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        if (startDataId > endDataId) {
                            return;
                        }
                        while (startDataId <= endDataId) {
                            try {
                                dataDao.insertDataToTable(programid, screenid, tableid, startDataId, show, pos);
                            } catch (SQLException ex) {
                                jTextArea2.append("Error adding dataids\n");
                                for (Throwable e : ex) {
                                    if (e instanceof SQLException) {
                                        e.printStackTrace(System.err);
                                        Throwable t = ex.getCause();
                                        while (t != null) {
                                            jTextArea2.append("Cause: " + t + "\n");
                                            t = t.getCause();
                                        }

                                    }
                                }
                            }
                            startDataId++;
                            pos++;
                            jTextArea2.append(".");
                        }
                        jTextArea2.append("\n");
                        jTextArea2.append("All data are added\n");
                    }
                }).start();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dataDao = new DataDaoImpl();

        if (fieldsNotEmtpty()) {
            if (jRadioButton1.isSelected()) {
                startDataId = Long.parseLong(txtStartDataId.getText());
                tableid = Long.parseLong(txtTableId.getText());
                screenid = Long.parseLong(txtScreenId.getText());
                programid = Long.parseLong(txtProgramId.getText());
                show = txtShow.getText();
                pos = Integer.parseInt(txtPos.getText());
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        try {
                            dataDao.removeDataFromTable(programid, screenid, tableid, startDataId);
                        } catch (SQLException ex) {
                            jTextArea2.append("Error adding dataids\n");
                            for (Throwable e : ex) {
                                if (e instanceof SQLException) {
                                    e.printStackTrace(System.err);
                                    Throwable t = ex.getCause();
                                    while (t != null) {
                                        jTextArea2.append("Cause: " + t + "\n");
                                        t = t.getCause();
                                    }

                                }
                            }
                        }
                        jTextArea2.append("All data are added\n");
                    }
                }).start();

            } else {
                startDataId = Long.parseLong(txtStartDataId.getText());
                endDataId = Long.parseLong(txtEndDataId.getText());
                tableid = Long.parseLong(txtTableId.getText());
                screenid = Long.parseLong(txtScreenId.getText());
                programid = Long.parseLong(txtProgramId.getText());
                show = txtShow.getText();
                pos = Integer.parseInt(txtPos.getText());
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        if (startDataId > endDataId) {
                            return;
                        }
                        while (startDataId <= endDataId) {
                            try {
                                dataDao.removeDataFromTable(programid, screenid, tableid, startDataId);
                            } catch (SQLException ex) {
                                jTextArea2.append("Error adding dataids\n");
                                for (Throwable e : ex) {
                                    if (e instanceof SQLException) {
                                        e.printStackTrace(System.err);
                                        Throwable t = ex.getCause();
                                        while (t != null) {
                                            jTextArea2.append("Cause: " + t + "\n");
                                            t = t.getCause();
                                        }

                                    }
                                }
                            }
                            startDataId++;
                            pos++;
                            jTextArea2.append(".");
                        }
                        jTextArea2.append("\n");
                        jTextArea2.append("All data are removed\n");
                    }
                }).start();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DBUtility().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtEndDataId;
    private javax.swing.JTextField txtPos;
    private javax.swing.JTextField txtProgramId;
    private javax.swing.JTextField txtScreenId;
    private javax.swing.JTextField txtShow;
    private javax.swing.JTextField txtStartDataId;
    private javax.swing.JTextField txtTableId;
    // End of variables declaration//GEN-END:variables

    private boolean fieldsNotEmtpty() {
        if (txtStartDataId.getText().equals("")
                || txtScreenId.getText().equals("")
                || txtTableId.getText().equals("")
                || txtPos.getText().equals("")
                || txtProgramId.getText().equals("")
                || txtShow.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }
}
